### ISSUE TITLE
Suggestion: add support to @angular/cli

### ISSUE THREAD

**Issue by beenotung** [trekhleb/ng-library-starter#10]
It maybe helpful to change the project into angular-cli project.

It may add complexity here but it can be ejected if not applicable.

**Comment by trekhleb** [comment]
@beenotung , thank you for suggestion. It may be the case of course but ideally I believe that Angular CLI itself will provide a possibility to generate component library as this feature request suggests https://github.com/angular/angular-cli/issues/1692.

**Comment by beenotung** [comment]
I integrated the generator from ionic cli and ionic cli. By default, the ionic stuff do not come with unit test.

basically just plug-in the .angular-cli.json from a new project (from template):
https://github.com/beenotung/ionic-horizon-seed/blob/master/.angular-cli.json

you can see the bash scripts gc, gs, gp to generate component, service, and pipe.
Would be better if I can integrate it into the cli using "native" way via JavaScript to be cross platform.
