### ISSUE TITLE
yarn build execute with error

### ISSUE THREAD

**Issue by Maden-maxi** [trekhleb/ng-library-starter#13]
Hello! I fork and clone repo to my machine do `yarn install` then `yarn build`.
After `yarn build` i get error

`
yarn run v1.2.1
$ rimraf dist tmp
$ npm run build:esm && npm run build:umd

> ngx-flipclock@0.0.0 build:esm /home/anonymous/Projects/ngx-flipclock
> gulp inline-templates && npm run ngcompile

Bus error (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 135
npm ERR! ngx-flipclock@0.0.0 build:esm: 'gulp inline-templates && npm run ngcompile'
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the ngx-flipclock@0.0.0 build:esm script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anonymous/.npm/_logs/2017-10-25T18_03_18_680Z-debug.log
error Command failed with exit code 135.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`
in log file

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/home/anonymous/.npm-global/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:esm' ]
2 info using npm@5.5.1
3 info using node@v6.11.5
4 verbose run-script [ 'prebuild:esm', 'build:esm', 'postbuild:esm' ]
5 info lifecycle ngx-flipclock@0.0.0~prebuild:esm: ngx-flipclock@0.0.0
6 info lifecycle ngx-flipclock@0.0.0~build:esm: ngx-flipclock@0.0.0
7 verbose lifecycle ngx-flipclock@0.0.0~build:esm: unsafe-perm in lifecycle true
8 verbose lifecycle ngx-flipclock@0.0.0~build:esm: PATH: /home/anonymous/.npm-global/lib/node_modules/npm/bin/node-gyp-bin:/home/anonymous/Projects/ngx-flipclock/node_modules/.bin:/home/anonymous/Projects/ngx-flipclock/node_modules/.bin:/home/anonymous/.config/yarn/link/node_modules/.bin:/home/anonymous/Projects/ngx-flipclock/node_modules/.bin:/home/anonymous/.config/yarn/link/node_modules/.bin:/usr/lib/node_modules/npm/bin/node-gyp-bin:/usr/bin/node_modules/npm/bin/node-gyp-bin:/home/anonymous/Programms/WebStorm-172.3757.55/bin:/home/anonymous/Programms/PhpStorm-172.3317.83/bin:/home/anonymous/.composer/vendor/bin:/opt/lampp:/opt/lampp/bin:/home/anonymous/.npm-global/bin:/home/anonymous/bin:/home/anonymous/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle ngx-flipclock@0.0.0~build:esm: CWD: /home/anonymous/Projects/ngx-flipclock
10 silly lifecycle ngx-flipclock@0.0.0~build:esm: Args: [ '-c', 'gulp inline-templates && npm run ngcompile' ]
11 silly lifecycle ngx-flipclock@0.0.0~build:esm: Returned: code: 135  signal: null
12 info lifecycle ngx-flipclock@0.0.0~build:esm: Failed to exec build:esm script
13 verbose stack Error: ngx-flipclock@0.0.0 build:esm: 'gulp inline-templates && npm run ngcompile'
13 verbose stack Exit status 135
13 verbose stack     at EventEmitter.<anonymous> (/home/anonymous/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:191:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/anonymous/.npm-global/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:920:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
14 verbose pkgid ngx-flipclock@0.0.0
15 verbose cwd /home/anonymous/Projects/ngx-flipclock
16 verbose Linux 4.10.0-37-generic
17 verbose argv "/usr/bin/node" "/home/anonymous/.npm-global/bin/npm" "run" "build:esm"
18 verbose node v6.11.5
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 135
22 error ngx-flipclock@0.0.0 build:esm: 'gulp inline-templates && npm run ngcompile'
22 error Exit status 135
23 error Failed at the ngx-flipclock@0.0.0 build:esm script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 135, true ]

Please help resolve my problem

**Comment by Kamilius** [comment]
@Maden-maxi 
Clearly a problem with some npm packages, which were built incorrectly or doesn't support your OS  at all:
- Try `rm -rf ./node_modules && yarn cache clean && yarn` (remove `node_modules`, clean `yarn cache` and `install yarn dependencies`.
- try using `npm install` instead of `yarn`, and if issue persists - rebuild packages for your OS via `npm rebuild`.
